---
name: Release

on:
  push:
    branches:
      - main

jobs:
  when_merged:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      repository-projects: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install dependencies
        run: npm install conventional-changelog-conventionalcommits -D
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          branch: main
          semantic_version: 19.0.5
          dry_run: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # should break after protecting the branch
      - name: New release version
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo release v${{ steps.semantic.outputs.new_release_version }}
