---
name: Dry-run Release

on: push

jobs:
  dry_run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      repository-projects: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Render terraform docs
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          config-file: .terraform-docs.yml
      - name: Set branch in .releaserc.yaml
        run: |
          cat <<EOF >> .releaserc.yaml
          branches:
            - $(git branch --show-current)
          EOF
      - name: Install dependencies
        run: npm install conventional-changelog-conventionalcommits -D
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          semantic_version: 19.0.5
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # should break after protecting the branch
      - name: New release version
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo release v${{ steps.semantic.outputs.new_release_version }}
